apiVersion: v1
kind: Secret
metadata:
  name: mysql-cred
  namespace: wordpress
type: Opaque
data:
  admin-password: YWRtaW5AMTIz # admin@123 
  username: Y3J1bmNob3Bz # crunchops 
  password: Y3J1bmNob3BzQDEyMw== # crunchops@123 
  db-name: d29yZHByZXNzX2Ri # wordpress_db 