apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: hello
    tier: frontend
spec:
  containers:
  - name: nginx
    image: "gcr.io/google-samples/hello-frontend:1.0"
    ports:
      - containerPort: 80
    # env:
    #  ... 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.kube
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend #  
            port:
              number: 80